Repository canonical/rebac-admin, pull requests merged in 2024-04, with the labels that each got.

#72 Upstream package/license changes
  HACKING.md
  LICENSE
  README.md
  package.json
  scripts/fetch-api-spec
  src/components/links/BaseLink/BaseLink.test.tsx
  src/components/links/BaseLink/BaseLink.tsx
  vite.config.ts
Labels: Review: Code +1

#78 WD-10055 - fix: make CI work for admin-service-api
  .github/workflows/actions.yml
  .github/workflows/test.yml
Labels: Review: Code needed

#77 WD-10024 - feat: set up views for groups and roles
  .gitignore
  openapi.yaml
  src/api/api.schemas.ts
  src/api/authentication-id/authentication-id.msw.ts
  src/api/authentication/authentication.msw.ts
  src/api/entitlements/entitlements.msw.ts
  src/api/groups-id/groups-id.msw.ts
  src/api/groups/groups.msw.ts
  src/api/resources/resources.msw.ts
  src/api/roles-id/roles-id.msw.ts
  src/api/roles/roles.msw.ts
  src/api/users-id/users-id.msw.ts
  src/api/users/users.msw.ts
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Groups/index.ts
  src/components/pages/Groups/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Roles/index.ts
  src/components/pages/Roles/types.ts
  src/components/pages/Users/Users.tsx
  src/mocks/groups.ts
  src/mocks/roles.ts
Labels: Review: QA needed, Review: Code needed

#79 WD-10154 - feat: add API proxy to prevent CORS issues
  .env
  HACKING.md
  package.json
  scripts/clean-files
  vite.config.ts
Labels: Review: Code +1

#80 WD-10192 - fix: turn off refetch when window is focused
  src/components/ReBACAdmin/ReBACAdmin.tsx
Labels: Review: QA +1, Review: Code +1

#81 WD-10180 - feature: add panel for creating roles
  README.md
  demo/src/App.tsx
  demo/src/main.tsx
  openapi.yaml
  package.json
  src/api/api.schemas.ts
  src/api/roles/roles.msw.ts
  src/api/roles/roles.ts
  src/components/Content/Content.tsx
  src/components/PanelForm/PanelForm.test.tsx
  src/components/PanelForm/PanelForm.tsx
  src/components/PanelForm/index.ts
  src/components/PanelForm/types.ts
  src/components/ReBACAdmin/ReBACAdmin.test.tsx
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/ToastCard/ToastCard.test.tsx
  src/components/ToastCard/ToastCard.tsx
  src/components/ToastCard/_toast-card.scss
  src/components/ToastCard/index.ts
  src/components/ToastCard/types.ts
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
  src/components/pages/Roles/AddRolePanel/index.ts
  src/components/pages/Roles/AddRolePanel/types.ts
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Roles/RolePanel/index.ts
  src/components/pages/Roles/RolePanel/types.ts
  src/components/pages/Roles/RolePanelButton/RolePanelButton.test.tsx
  src/components/pages/Roles/RolePanelButton/RolePanelButton.tsx
  src/components/pages/Roles/RolePanelButton/index.ts
  src/components/pages/Roles/RolePanelButton/types.ts
  src/components/pages/Roles/Roles.tsx
  src/context/ReBACAdminContext.ts
  src/hooks/index.ts
  src/hooks/usePanelPortal.test.tsx
  src/hooks/usePanelPortal.ts
  src/mocks/roles.ts
  src/test/ComponentProviders.tsx
  src/test/utils.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#85 WD-10233 - refactor: rebuild mocks and delays
  .env
  orval.config.ts
  package.json
  src/api/api.schemas.ts
  src/api/authentication-id/authentication-id.msw.ts
  src/api/authentication-id/authentication-id.ts
  src/api/authentication/authentication.msw.ts
  src/api/authentication/authentication.ts
  src/api/entitlements/entitlements.msw.ts
  src/api/entitlements/entitlements.ts
  src/api/groups-id/groups-id.msw.ts
  src/api/groups-id/groups-id.ts
  src/api/groups/groups.msw.ts
  src/api/groups/groups.ts
  src/api/resources/resources.msw.ts
  src/api/resources/resources.ts
  src/api/roles-id/roles-id.msw.ts
  src/api/roles-id/roles-id.ts
  src/api/roles/roles.msw.ts
  src/api/roles/roles.ts
  src/api/users-id/users-id.msw.ts
  src/api/users-id/users-id.ts
  src/api/users/users.msw.ts
  src/api/users/users.ts
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Users/Users.test.tsx
  src/mocks/groups.ts
  src/mocks/roles.ts
  src/mocks/users.ts
  yarn.lock
Labels: Review: Code +1

#84 WD-10181 - feature: add entitlements when creating a role
  openapi.yaml
  src/api/api.schemas.ts
  src/api/roles-id/roles-id.msw.ts
  src/api/roles-id/roles-id.ts
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
  src/components/EntitlementsPanelForm/_entitlements-panel-form.scss
  src/components/EntitlementsPanelForm/index.ts
  src/components/EntitlementsPanelForm/types.ts
  src/components/FormikSubmitButton/FormikSubmitButton.test.tsx
  src/components/FormikSubmitButton/FormikSubmitButton.tsx
  src/components/FormikSubmitButton/index.ts
  src/components/FormikSubmitButton/types.ts
  src/components/PanelForm/PanelForm.test.tsx
  src/components/PanelForm/PanelForm.tsx
  src/components/PanelForm/PanelFormLink/PanelFormLink.test.tsx
  src/components/PanelForm/PanelFormLink/PanelFormLink.tsx
  src/components/PanelForm/PanelFormLink/_panel-form-link.scss
  src/components/PanelForm/PanelFormLink/index.ts
  src/components/PanelForm/PanelFormLink/types.ts
  src/components/PanelForm/PanelFormLink/utils.test.ts
  src/components/PanelForm/PanelFormLink/utils.ts
  src/components/PanelForm/PanelFormNavigation/PanelFormNavigation.test.tsx
  src/components/PanelForm/PanelFormNavigation/PanelFormNavigation.tsx
  src/components/PanelForm/PanelFormNavigation/_panel-form-navigation.scss
  src/components/PanelForm/PanelFormNavigation/consts.ts
  src/components/PanelForm/PanelFormNavigation/index.ts
  src/components/PanelForm/PanelFormNavigation/types.ts
  src/components/PanelForm/types.ts
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Roles/RolePanel/types.ts
  src/components/pages/Roles/RolePanelButton/RolePanelButton.test.tsx
  src/components/pages/Roles/RolePanelButton/RolePanelButton.tsx
  src/hooks/usePanelPortal.test.tsx
  src/hooks/usePanelPortal.ts
  src/scss/index.scss
  src/test/setup.ts
  src/test/utils.tsx
Labels: Review: QA +1, Review: Code +1

#82 WD-10176 - fix: update API types
  openapi.yaml
  src/api/api.schemas.ts
  src/api/groups-id/groups-id.msw.ts
  src/api/groups-id/groups-id.ts
  src/api/groups/groups.msw.ts
  src/api/groups/groups.ts
  src/api/roles-id/roles-id.msw.ts
  src/api/roles-id/roles-id.ts
Labels: Review: Code +1

#86 WD-10182 - Update role entitlements
  package.json
  src/async-limiter.d.ts
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
  src/components/EntitlementsPanelForm/types.ts
  src/components/FormikSubmitButton/FormikSubmitButton.test.tsx
  src/components/FormikSubmitButton/FormikSubmitButton.tsx
  src/components/FormikSubmitButton/types.ts
  src/components/PanelForm/PanelForm.tsx
  src/components/PanelForm/types.ts
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
  src/components/pages/Roles/EditRolePanel/index.ts
  src/components/pages/Roles/EditRolePanel/types.ts
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Roles/RolePanel/types.ts
  src/components/pages/Roles/RolePanelButton/RolePanelButton.test.tsx
  src/components/pages/Roles/RolePanelButton/RolePanelButton.tsx
  src/components/pages/Roles/RolePanelButton/index.ts
  src/components/pages/Roles/RolePanelButton/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Roles/types.ts
  src/consts.ts
  src/scss/index.scss
  yarn.lock
Labels: Review: QA needed, Review: Code +1

#90 WD-10346 - fix: prevent form panels from closing when clicking outside/pressing escape
  src/hooks/usePanelPortal.test.tsx
  src/hooks/usePanelPortal.ts
Labels: Review: QA +1, Review: Code +1

#87 WD-10178 - feat: Add EmptyState for roles and groups
  src/components/NoEntityCard/NoEntityCard.test.tsx
  src/components/NoEntityCard/NoEntityCard.tsx
  src/components/NoEntityCard/_no-entity-card.scss
  src/components/NoEntityCard/index.ts
  src/components/NoEntityCard/types.ts
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Groups/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Roles/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#91 WD-10186 - feat: add user form to group panel
  openapi.yaml
  package.json
  src/api/api.schemas.ts
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
  src/components/pages/Groups/AddGroupPanel/types.ts
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Groups/GroupPanel/types.ts
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
  src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
  src/components/pages/Groups/IdentitiesPanelForm/index.ts
  src/components/pages/Groups/IdentitiesPanelForm/types.ts
  src/test/ComponentProviders.tsx
Labels: Review: QA +1, Review: Code +1

#92 WD-10187 - feat: add role form to group panel
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
  src/components/pages/Groups/AddGroupPanel/types.ts
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Groups/GroupPanel/types.ts
  src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
  src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
  src/components/pages/Groups/RolesPanelForm/index.ts
  src/components/pages/Groups/RolesPanelForm/types.ts
  src/scss/index.scss
Labels: Review: QA +1, Review: Code +1

#94 WD-10189 - feat: edit a group's users
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/EditGroupPanel/types.ts
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
Labels: Review: QA +1, Review: Code +1
