Repository canonical/rebac-admin, pull requests merged in 2024-09, with the labels that each got.

#163 WD-13090 - feat: update table columns
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Groups/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Roles/types.ts
  src/components/pages/Users/Users.test.tsx
  src/components/pages/Users/Users.tsx
  src/components/pages/Users/types.ts
  src/test/queries/tables.ts
  src/test/queries/within.ts
  src/test/utils.tsx
Labels: Review: QA +1, Review: Code +1

#164 WD-14600 - test: add custom queries for testing for notifications and spinners
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
  src/components/GroupsPanelForm/GroupsPanelForm.test.tsx
  src/components/MultiSelectField/MultiSelectField.test.tsx
  src/components/PanelForm/PanelForm.test.tsx
  src/components/PanelTableForm/PanelTableForm.test.tsx
  src/components/RolesPanelForm/RolesPanelForm.test.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/DeleteGroupsModal/DeleteGroupsModal.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/DeleteRolesModal/DeleteRolesModal.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
  src/components/pages/Users/DeleteUsersModal/DeleteUsersModal.test.tsx
  src/components/pages/Users/EntitlementsTab/EntitlementsTab.test.tsx
  src/components/pages/Users/GroupsTab/GroupsTab.test.tsx
  src/components/pages/Users/RolesTab/RolesTab.test.tsx
  src/test/queries/index.ts
  src/test/queries/notifications.ts
  src/test/queries/queries.ts
  src/test/queries/spinners.ts
  src/test/queries/within.ts
  src/test/utils.tsx
Labels: Review: Code +1

#160 WD-12398 - feat: add user's entitlements form to edit panel
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
  src/components/pages/Users/EditUserPanel/index.ts
  src/components/pages/Users/EditUserPanel/types.ts
  src/components/pages/Users/UserPanel/UserPanel.test.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
  src/components/pages/Users/UserPanel/types.ts
  src/components/pages/Users/Users.test.tsx
  src/components/pages/Users/Users.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#165 WD-14646 - ci: set coverage threshold
  .gitignore
  demo/src/mockApiWorker.ts
  scripts/serve-mock-api.ts
  src/components/CheckCapability/CheckCapability.test.tsx
  src/components/Content/Content.test.tsx
  src/components/GroupsPanelForm/GroupsPanelForm.test.tsx
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
  src/components/pages/Users/EntitlementsTab/EntitlementsTab.test.tsx
  src/components/pages/Users/GroupsTab/GroupsTab.test.tsx
  src/components/pages/Users/SummaryTab/SummaryTab.test.tsx
  src/components/pages/Users/User/User.test.tsx
  src/components/pages/Users/Users.test.tsx
  src/hooks/capabilities.test.tsx
  src/hooks/usePagination.test.tsx
  src/test/mocks/capabilities.ts
  src/test/mocks/common.ts
  src/test/mocks/entitlements.ts
  src/test/mocks/groups.ts
  src/test/mocks/handlers.ts
  src/test/mocks/identities.ts
  src/test/mocks/resources.ts
  src/test/mocks/roles.ts
  vite.config.ts
Labels: Review: Code +1

#167 WD-12396 - feat: add edit user's groups form to edit panel
  src/components/GroupsPanelForm/index.ts
  src/components/RolesPanelForm/index.ts
  src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
  src/components/pages/Users/EditUserPanel/types.ts
  src/components/pages/Users/UserPanel/UserPanel.test.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
  src/components/pages/Users/UserPanel/types.ts
Labels: Review: QA +1, Review: Code +1

#168 WD-12397 - feat: add edit user's roles form to edit panel
  src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
  src/components/pages/Users/EditUserPanel/types.ts
  src/components/pages/Users/UserPanel/UserPanel.test.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
  src/components/pages/Users/UserPanel/types.ts
Labels: Review: QA +1, Review: Code +1

#169 WD-14680 - feat: add entitlements page
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Entitlements/Entitlements.test.tsx
  src/components/pages/Entitlements/Entitlements.tsx
  src/components/pages/Entitlements/index.ts
  src/components/pages/Entitlements/types.ts
Labels: Review: QA +1, Review: Code +1

#170 WD-14684 - feat: add resources page
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Entitlements/Entitlements.test.tsx
  src/components/pages/Resources/Resources.test.tsx
  src/components/pages/Resources/Resources.tsx
  src/components/pages/Resources/index.ts
  src/components/pages/Resources/types.ts
Labels: Review: QA +1, Review: Code +1

#172 WD-14784 - fix: reload updated queries
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
Labels: Review: QA +1, Review: Code +1

#173 WD-12405 - feat: add user details edit form
  src/components/pages/Users/User/User.test.tsx
  src/components/pages/Users/User/User.tsx
  src/components/pages/Users/User/types.ts
  src/components/pages/Users/UserPanel/UserPanel.test.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
Labels: Review: QA +1, Review: Code +1

#180 feat: edit role name
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
  src/components/pages/Roles/EditRolePanel/types.ts
  src/components/pages/Roles/RolePanel/Fields/Fields.test.tsx
  src/components/pages/Roles/RolePanel/Fields/Fields.tsx
  src/components/pages/Roles/RolePanel/Fields/index.ts
  src/components/pages/Roles/RolePanel/Fields/types.ts
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Roles/RolePanel/types.ts
  src/components/pages/Roles/Roles.tsx
Labels: Review: QA +1, Review: Code +1

#175 WD-14894 - feat: update user details in edit form
  src/components/pages/Users/AddUserPanel/AddUserPanel.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.test.tsx
  src/components/pages/Users/EditUserPanel/EditUserPanel.tsx
  src/components/pages/Users/EditUserPanel/types.ts
  src/components/pages/Users/User/User.tsx
  src/components/pages/Users/UserPanel/Fields/Fields.test.tsx
  src/components/pages/Users/UserPanel/Fields/Fields.tsx
  src/components/pages/Users/UserPanel/Fields/index.ts
  src/components/pages/Users/UserPanel/Fields/types.ts
  src/components/pages/Users/UserPanel/UserPanel.test.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
  src/components/pages/Users/UserPanel/index.ts
  src/components/pages/Users/UserPanel/types.ts
  src/components/pages/Users/Users.tsx
Labels: Review: QA +1, Review: Code +1 (with changes)

#181 WD-14896 - feat: update group name in edit form
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/EditGroupPanel/types.ts
  src/components/pages/Groups/GroupPanel/Fields/Fields.test.tsx
  src/components/pages/Groups/GroupPanel/Fields/Fields.tsx
  src/components/pages/Groups/GroupPanel/Fields/index.ts
  src/components/pages/Groups/GroupPanel/Fields/types.ts
  src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Groups/GroupPanel/index.ts
  src/components/pages/Groups/GroupPanel/types.ts
  src/components/pages/Groups/Groups.tsx
Labels: Review: QA +1, Review: Code +1
