Repository canonical/rebac-admin, pull requests merged in 2024-05, with the labels that each got.

#96 WD-10190 - feat: edit roles for a group
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/Groups.test.tsx
Labels: Review: QA +1, Review: Code +1

#97 WD-10954 - feat: support changing panel widths
  src/components/SubFormPanel/PanelFormNavigation/PanelFormNavigation.test.tsx
  src/components/SubFormPanel/PanelFormNavigation/PanelFormNavigation.tsx
  src/components/SubFormPanel/PanelFormNavigation/types.ts
  src/components/SubFormPanel/SubFormPanel.test.tsx
  src/components/SubFormPanel/SubFormPanel.tsx
  src/components/SubFormPanel/types.ts
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
  src/components/pages/Groups/AddGroupPanel/types.ts
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/EditGroupPanel/types.ts
  src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Groups/GroupPanel/types.ts
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
  src/components/pages/Roles/AddRolePanel/types.ts
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
  src/components/pages/Roles/EditRolePanel/types.ts
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Roles/RolePanel/types.ts
  src/components/pages/Roles/Roles.tsx
  src/hooks/usePanel.test.tsx
  src/hooks/usePanel.tsx
  src/hooks/usePanelPortal.ts
Labels: Review: QA +1, Review: Code +1

#99 WD-10968 - fix: fix test websocket errors
  src/components/ReBACAdmin/ReBACAdmin.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
Labels: Review: QA +1, Review: Code +1

#93 WD-10179 - feat: add delete roles and groups panel
  src/components/DeleteEntityPanel/DeleteEntityPanel.test.tsx
  src/components/DeleteEntityPanel/DeleteEntityPanel.tsx
  src/components/DeleteEntityPanel/index.ts
  src/components/DeleteEntityPanel/types.ts
  src/components/PanelForm/PanelForm.tsx
  src/components/PanelForm/types.ts
  src/components/pages/Groups/DeleteGroupsPanel/DeleteGroupsPanel.test.tsx
  src/components/pages/Groups/DeleteGroupsPanel/DeleteGroupsPanel.tsx
  src/components/pages/Groups/DeleteGroupsPanel/index.ts
  src/components/pages/Groups/DeleteGroupsPanel/types.ts
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Groups/types.ts
  src/components/pages/Roles/DeleteRolesPanel/DeleteRolesPanel.test.tsx
  src/components/pages/Roles/DeleteRolesPanel/DeleteRolesPanel.tsx
  src/components/pages/Roles/DeleteRolesPanel/index.ts
  src/components/pages/Roles/DeleteRolesPanel/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Roles/types.ts
  src/hooks/index.ts
  src/hooks/useEntitiesSelect.test.ts
  src/hooks/useEntitiesSelect.ts
  src/hooks/usePanel.tsx
  src/scss/_tables.scss
  src/scss/index.scss
Labels: Review: QA +1, Review: Code +1 (with changes)

#100 WD-10993 - feat: only display errors on dirty forms
  src/components/CleanFormikField/CleanFormikField.test.tsx
  src/components/CleanFormikField/CleanFormikField.tsx
  src/components/CleanFormikField/index.ts
  src/components/CleanFormikField/types.ts
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
  src/components/PanelForm/PanelForm.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
  src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
Labels: Review: QA +1, Review: Code +1

#101 WD-10969 - refactor: make reusable table/form component
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
  src/components/EntitlementsPanelForm/types.ts
  src/components/PanelTableForm/PanelTableForm.test.tsx
  src/components/PanelTableForm/PanelTableForm.tsx
  src/components/PanelTableForm/_panel-table-form.scss
  src/components/PanelTableForm/index.ts
  src/components/PanelTableForm/types.ts
  src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.test.tsx
  src/components/pages/Groups/IdentitiesPanelForm/IdentitiesPanelForm.tsx
  src/components/pages/Groups/IdentitiesPanelForm/types.ts
  src/components/pages/Groups/RolesPanelForm/RolesPanelForm.test.tsx
  src/components/pages/Groups/RolesPanelForm/RolesPanelForm.tsx
  src/components/pages/Groups/RolesPanelForm/types.ts
Labels: Review: QA +1, Review: Code +1

#102 WD-10992 - refactor: support name fields
  openapi.yaml
  src/api/api.schemas.ts
  src/api/groups-id/groups-id.msw.ts
  src/api/groups-id/groups-id.ts
  src/api/groups/groups.msw.ts
  src/api/groups/groups.ts
  src/api/roles-id/roles-id.msw.ts
  src/api/roles/roles.msw.ts
  src/api/roles/roles.ts
  src/components/SubFormPanel/SubFormPanel.test.tsx
  src/components/SubFormPanel/SubFormPanel.tsx
  src/components/SubFormPanel/types.ts
  src/components/ToastCard/ToastCard.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Groups/GroupPanel/types.ts
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Roles/RolePanel/types.ts
  src/components/pages/Roles/Roles.test.tsx
Labels: Review: Code +1

#108 WD-11350 - refactor: simplify creating panels
  demo/src/App.tsx
  demo/src/main.tsx
  src/components/EmbeddedPanel/EmbeddedPanel.test.tsx
  src/components/EmbeddedPanel/EmbeddedPanel.tsx
  src/components/EmbeddedPanel/consts.ts
  src/components/EmbeddedPanel/index.ts
  src/components/EmbeddedPanel/types.ts
  src/components/FormPanel/FormPanel.tsx
  src/components/FormPanel/types.ts
  src/components/Panel/Panel.tsx
  src/components/SubFormPanel/PanelFormNavigation/PanelFormNavigation.tsx
  src/components/SubFormPanel/SubFormPanel.tsx
  src/consts.ts
  src/hooks/usePanel.test.tsx
  src/hooks/usePanel.tsx
  src/hooks/usePanelPortal.test.tsx
  src/hooks/usePanelPortal.ts
Labels: Review: QA +1, Review: Code +1

#110 WD-11353 - ci: add TICS reporting
  .github/workflows/tics-coverage.yml
  vite.config.ts
Labels: Review: Code +1

#111 fix: upload coverage artefact
  .github/workflows/tics-coverage.yml
Labels: Review: Code +1

#109 WD-11566 - fix: add padding to loading state in SubFormPanel
  package.json
  src/components/CleanFormikField/CleanFormikField.test.tsx
  src/components/NoEntityCard/NoEntityCard.test.tsx
  src/components/NoEntityCard/NoEntityCard.tsx
  src/components/PanelTableForm/PanelTableForm.test.tsx
  src/components/SubFormPanel/SubFormPanel.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1 (with changes)
