Repository canonical/rebac-admin, pull requests merged in 2024-07, with the labels that each got.

#122 WD-12389 - feat: edit role panel
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.tsx
  src/components/pages/Roles/EditRolePanel/index.ts
  src/components/pages/Roles/EditRolePanel/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
Labels: Review: QA +1, Review: Code +1

#121 WD-12386 - feat: delete groups panel
  src/components/DeleteEntityPanel/DeleteEntityPanel.test.tsx
  src/components/DeleteEntityPanel/DeleteEntityPanel.tsx
  src/components/DeleteEntityPanel/index.ts
  src/components/DeleteEntityPanel/types.ts
  src/components/FormPanel/FormPanel.test.tsx
  src/components/FormPanel/FormPanel.tsx
  src/components/FormPanel/index.ts
  src/components/FormPanel/types.ts
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/AddGroupPanel/types.ts
  src/components/pages/Groups/DeleteGroupsPanel/DeleteGroupsPanel.test.tsx
  src/components/pages/Groups/DeleteGroupsPanel/DeleteGroupsPanel.tsx
  src/components/pages/Groups/DeleteGroupsPanel/index.ts
  src/components/pages/Groups/DeleteGroupsPanel/types.ts
  src/components/pages/Groups/EditGroupPanel/types.ts
  src/components/pages/Groups/GroupPanel/index.ts
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
Labels: Review: QA +1, Review: Code +1

#123 WD-12390 - feat: delete role panel
  src/components/pages/Roles/DeleteRolesPanel/DeleteRolesPanel.test.tsx
  src/components/pages/Roles/DeleteRolesPanel/DeleteRolesPanel.tsx
  src/components/pages/Roles/DeleteRolesPanel/index.ts
  src/components/pages/Roles/DeleteRolesPanel/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
Labels: Review: QA +1, Review: Code +1

#124 WD-12970 - fix: display panels when there is no data
  .github/workflows/actions.yml
  package.json
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Groups/types.ts
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Roles/types.ts
Labels: Review: QA +1, Review: Code +1

#125 WD-12971 - fix: display panels when there is no data
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
Labels: Review: QA +1, Review: Code +1

#126 WD-12608 - refactor: merge calls for updating roles
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
Labels: Review: Code +1

#127 WD-12607 - refactor: merge calls for updating identities
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
Labels: Review: Code +1

#130 WD-12391 - feat: delete users panel
  src/components/SubFormPanel/index.ts
  src/components/pages/Users/DeleteUsersPanel/DeleteUsersPanel.test.tsx
  src/components/pages/Users/DeleteUsersPanel/DeleteUsersPanel.tsx
  src/components/pages/Users/DeleteUsersPanel/index.ts
  src/components/pages/Users/DeleteUsersPanel/types.ts
  src/components/pages/Users/UserPanel/index.ts
  src/components/pages/Users/UserPanel/types.ts
  src/components/pages/Users/Users.test.tsx
  src/components/pages/Users/Users.tsx
  src/components/pages/Users/types.ts
Labels: Review: QA +1, Review: Code +1

#106 WD-12910 - Use application layout from react-components
  demo/src/App.tsx
  demo/src/components/ApplicationLayout/AppAside/AppAside.test.tsx
  demo/src/components/ApplicationLayout/AppAside/AppAside.tsx
  demo/src/components/ApplicationLayout/AppAside/index.ts
  demo/src/components/ApplicationLayout/AppMain/AppMain.test.tsx
  demo/src/components/ApplicationLayout/AppMain/AppMain.tsx
  demo/src/components/ApplicationLayout/AppMain/index.ts
  demo/src/components/ApplicationLayout/AppNavigation/AppNavigation.test.tsx
  demo/src/components/ApplicationLayout/AppNavigation/AppNavigation.tsx
  demo/src/components/ApplicationLayout/AppNavigation/index.ts
  demo/src/components/ApplicationLayout/AppNavigationBar/AppNavigationBar.test.tsx
  demo/src/components/ApplicationLayout/AppNavigationBar/AppNavigationBar.tsx
  demo/src/components/ApplicationLayout/AppNavigationBar/index.ts
  demo/src/components/ApplicationLayout/AppStatus/AppStatus.test.tsx
  demo/src/components/ApplicationLayout/AppStatus/AppStatus.tsx
  demo/src/components/ApplicationLayout/AppStatus/index.ts
  demo/src/components/ApplicationLayout/Application/Application.test.tsx
  demo/src/components/ApplicationLayout/Application/Application.tsx
  demo/src/components/ApplicationLayout/Application/index.ts
  demo/src/components/ApplicationLayout/ApplicationLayout.test.tsx
  demo/src/components/ApplicationLayout/ApplicationLayout.tsx
  demo/src/components/ApplicationLayout/index.ts
  demo/src/components/SideNavigation/SideNavigation.test.tsx
  demo/src/components/SideNavigation/SideNavigation.tsx
  demo/src/components/SideNavigation/SideNavigationItem/SideNavigationItem.test.tsx
  demo/src/components/SideNavigation/SideNavigationItem/SideNavigationItem.tsx
  demo/src/components/SideNavigation/SideNavigationItem/index.ts
  demo/src/components/SideNavigation/SideNavigationLink/SideNavigationLink.test.tsx
  demo/src/components/SideNavigation/SideNavigationLink/SideNavigationLink.tsx
  demo/src/components/SideNavigation/SideNavigationLink/index.ts
  demo/src/components/SideNavigation/index.ts
  demo/src/main.tsx
  package.json
  src/components/Content/Content.tsx
  src/components/FormPanel/FormPanel.tsx
  src/components/FormPanel/types.ts
  src/components/Panel/Panel.test.tsx
  src/components/Panel/Panel.tsx
  src/components/Panel/index.ts
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/SubFormPanel/SubFormPanel.tsx
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#133 WD-13089 - refactor: built latest API spec
  src/api/groups/groups.msw.ts
  src/api/groups/groups.ts
  src/api/roles/roles.msw.ts
  src/api/roles/roles.ts
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.tsx
Labels: Review: QA +1, Review: Code +1

#132 WD-12409 - feat: set up user details
  src/components/BreadcrumbNavigation/BreadcrumbNavigation.test.tsx
  src/components/BreadcrumbNavigation/BreadcrumbNavigation.tsx
  src/components/BreadcrumbNavigation/_breadcrumb-navigation.scss
  src/components/BreadcrumbNavigation/index.ts
  src/components/BreadcrumbNavigation/types.ts
  src/components/Content/Content.tsx
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/SubFormPanel/PanelFormNavigation/PanelFormNavigation.tsx
  src/components/SubFormPanel/PanelFormNavigation/_panel-form-navigation.scss
  src/components/pages/Users/User/User.test.tsx
  src/components/pages/Users/User/User.tsx
  src/components/pages/Users/User/index.ts
  src/components/pages/Users/User/types.ts
  src/components/pages/Users/Users.test.tsx
  src/components/pages/Users/Users.tsx
  src/scss/index.scss
  src/test/ComponentProviders.tsx
  src/test/utils.tsx
  src/urls.ts
Labels: Review: QA +1, Review: Code +1

#134 WD-12392 - feat: add basic create user panel
  src/components/pages/Users/AddUserPanel/AddUserPanel.test.tsx
  src/components/pages/Users/AddUserPanel/AddUserPanel.tsx
  src/components/pages/Users/AddUserPanel/index.ts
  src/components/pages/Users/UserPanel/UserPanel.test.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
  src/components/pages/Users/UserPanel/index.ts
  src/components/pages/Users/UserPanel/types.ts
  src/components/pages/Users/Users.test.tsx
  src/components/pages/Users/Users.tsx
  src/components/pages/Users/types.ts
Labels: Review: QA +1, Review: Code +1 (with changes)

#138 WD-13334 - feat: make all panels medium width
  src/components/SubFormPanel/SubFormPanel.test.tsx
  src/components/SubFormPanel/SubFormPanel.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.tsx
  src/components/pages/Roles/RolePanel/RolePanel.tsx
  src/components/pages/Users/UserPanel/UserPanel.tsx
Labels: Review: QA +1, Review: Code +1

#137 feat: add user summary
  src/components/ListCard/ListCard.test.tsx
  src/components/ListCard/ListCard.tsx
  src/components/ListCard/ListCardList/ListCardList.test.tsx
  src/components/ListCard/ListCardList/ListCardList.tsx
  src/components/ListCard/ListCardList/_list-card-list.scss
  src/components/ListCard/ListCardList/index.ts
  src/components/ListCard/ListCardList/types.ts
  src/components/ListCard/_list-card.scss
  src/components/ListCard/index.ts
  src/components/ListCard/types.ts
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/pages/Users/SummaryTab/SummaryTab.test.tsx
  src/components/pages/Users/SummaryTab/SummaryTab.tsx
  src/components/pages/Users/SummaryTab/index.ts
  src/components/pages/Users/SummaryTab/types.ts
Labels: Review: QA +1, Review: Code +1

#139 WD-13336 - feat: add search to users, roles and groups
  src/components/Content/Content.test.tsx
  src/components/Content/Content.tsx
  src/components/Content/_content.scss
  src/components/pages/Groups/Groups.test.tsx
  src/components/pages/Groups/Groups.tsx
  src/components/pages/Roles/Roles.test.tsx
  src/components/pages/Roles/Roles.tsx
  src/components/pages/Users/Users.test.tsx
  src/components/pages/Users/Users.tsx
Labels: Review: QA +1, Review: Code +1

#142 WD-13635 - feat: support parent query context
  README.md
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/ReBACAdmin/types.ts
  src/test/utils.tsx
Labels: Review: Code +1

#141 WD-13634 - feat: support parent query context
  README.md
  src/components/ReBACAdmin/ReBACAdmin.tsx
  src/components/ReBACAdmin/types.ts
  src/test/utils.tsx
Labels: Review: Code +1

#136 WD-12648 - feat: update entitlements forms to select from existing entitlements
  src/api/api.schemas.ts
  src/api/entitlements/entitlements.msw.ts
  src/api/groups/groups.msw.ts
  src/api/identities/identities.msw.ts
  src/api/resources/resources.msw.ts
  src/api/roles/roles.msw.ts
  src/components/CleanFormikField/index.ts
  src/components/CleanFormikField/types.ts
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.test.tsx
  src/components/EntitlementsPanelForm/EntitlementsPanelForm.tsx
  src/components/EntitlementsPanelForm/Fields/Fields.test.tsx
  src/components/EntitlementsPanelForm/Fields/Fields.tsx
  src/components/EntitlementsPanelForm/Fields/index.ts
  src/components/EntitlementsPanelForm/Fields/types.ts
  src/components/EntitlementsPanelForm/index.ts
  src/components/EntitlementsPanelForm/types.ts
  src/components/PanelTableForm/PanelTableForm.test.tsx
  src/components/PanelTableForm/PanelTableForm.tsx
  src/components/PanelTableForm/types.ts
  src/components/pages/Groups/AddGroupPanel/AddGroupPanel.test.tsx
  src/components/pages/Groups/EditGroupPanel/EditGroupPanel.test.tsx
  src/components/pages/Groups/GroupPanel/GroupPanel.test.tsx
  src/components/pages/Roles/AddRolePanel/AddRolePanel.test.tsx
  src/components/pages/Roles/EditRolePanel/EditRolePanel.test.tsx
  src/components/pages/Roles/RolePanel/RolePanel.test.tsx
  src/utils/index.ts
  src/utils/pluralize.test.ts
  src/utils/pluralize.ts
Labels: Review: QA +1, Review: Code +1 (with changes)
